1. Carregar agora os dados dos dois datasets utilizando um DateTimeIndex ;

In [1]:
import pandas as pd
import numpy as np

dataframe2003 = pd.read_csv('./datasets/INMET_CO_MT_A901_CUIABA_01-01-2003_A_31-12-2003.CSV', sep=';', encoding='ISO-8859-1' , decimal = ',')
dataframe2013 = pd.read_csv('./datasets/INMET_CO_MT_A901_CUIABA_01-01-2013_A_31-12-2013.CSV', sep=';', encoding='ISO-8859-1', decimal = ',')
dataframe2023 = pd.read_csv('./datasets/INMET_CO_MT_A901_CUIABA_01-01-2023_A_31-12-2023.CSV', sep=';', encoding='ISO-8859-1', decimal = ',')

In [2]:
dataframe2003.head()

,DATA,HORA (UTC),"PRECIPITAÇÃO TOTAL, HORÁRIO (MM)","PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)",PRESSÇO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB),PRESSÇO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB),RADIACAO GLOBAL (KJ/mý),"TEMPERATURA DO AR - BULBO SECO, HORARIA (øC)",TEMPERATURA DO PONTO DE ORVALHO (øC),TEMPERATURA MµXIMA NA HORA ANT. (AUT) (øC),TEMPERATURA MÖNIMA NA HORA ANT. (AUT) (øC),TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (øC),TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (øC),UMIDADE REL. MAX. NA HORA ANT. (AUT) (%),UMIDADE REL. MIN. NA HORA ANT. (AUT) (%),"UMIDADE RELATIVA DO AR, HORARIA (%)","VENTO, DIREÇO HORARIA (gr) (ø (gr))","VENTO, RAJADA MAXIMA (m/s)","VENTO, VELOCIDADE HORARIA (m/s)"
0,01/01/2003,00:00,-9999.0,-9999.0,-9999.0,-9999.0,-9999,24.3,23.3,24.7,24.3,23.4,-9999.0,94,92,94,-9999,-9999.0,-9999.0
1,01/01/2003,01:00,-9999.0,-9999.0,-9999.0,-9999.0,-9999,24.7,23.3,24.7,24.3,23.4,-9999.0,94,92,92,-9999,-9999.0,-9999.0
2,01/01/2003,02:00,-9999.0,-9999.0,-9999.0,-9999.0,-9999,24.4,23.2,24.7,24.4,23.4,-9999.0,93,91,93,-9999,-9999.0,-9999.0
3,01/01/2003,03:00,-9999.0,-9999.0,-9999.0,-9999.0,-9999,24.1,23.2,24.9,24.1,23.5,-9999.0,95,92,95,-9999,-9999.0,-9999.0
4,01/01/2003,04:00,-9999.0,-9999.0,-9999.0,-9999.0,-9999,24.5,23.4,24.6,24.1,23.5,-9999.0,95,93,94,-9999,-9999.0,-9999.0

In [3]:
dataframe2013.head()

,DATA,HORA (UTC),"PRECIPITAÇÃO TOTAL, HORÁRIO (mm)","PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)",PRESSÇO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB),PRESSÇO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB),RADIACAO GLOBAL (KJ/mý),"TEMPERATURA DO AR - BULBO SECO, HORARIA (øC)",TEMPERATURA DO PONTO DE ORVALHO (øC),TEMPERATURA MµXIMA NA HORA ANT. (AUT) (øC),TEMPERATURA MÖNIMA NA HORA ANT. (AUT) (øC),TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (øC),TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (øC),UMIDADE REL. MAX. NA HORA ANT. (AUT) (%),UMIDADE REL. MIN. NA HORA ANT. (AUT) (%),"UMIDADE RELATIVA DO AR, HORARIA (%)","VENTO, DIREÇO HORARIA (gr) (ø (gr))","VENTO, RAJADA MAXIMA (m/s)","VENTO, VELOCIDADE HORARIA (m/s)"
0,01/01/2013,00:00,0.4,983.5,983.5,982.1,-9999.0,26.1,21.9,28.1,26.1,22.0,20.7,78,64,78,145,4.3,2.1
1,01/01/2013,01:00,1.2,983.9,984.0,983.5,-9999.0,24.7,22.7,26.1,24.5,22.9,22.2,89,78,89,184,4.0,1.4
2,01/01/2013,02:00,0.4,984.4,984.5,983.9,-9999.0,24.5,22.8,24.9,24.5,23.2,22.5,91,88,91,247,3.7,1.6
3,01/01/2013,03:00,0.0,984.9,985.0,984.4,-9999.0,24.4,22.9,24.5,24.2,22.9,22.5,92,90,92,98,3.5,1.9
4,01/01/2013,04:00,0.0,984.3,984.9,984.3,-9999.0,24.4,22.9,24.4,24.2,23.0,22.8,92,91,91,123,3.5,1.2

In [4]:
dataframe2023.head()

,DATA,Hora UTC,"PRECIPITAÇÃO TOTAL, HORÁRIO (mm)","PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)",PRESSÇO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB),PRESSÇO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB),RADIACAO GLOBAL (Kj/mý),"TEMPERATURA DO AR - BULBO SECO, HORARIA (øC)",TEMPERATURA DO PONTO DE ORVALHO (øC),TEMPERATURA MµXIMA NA HORA ANT. (AUT) (øC),TEMPERATURA MÖNIMA NA HORA ANT. (AUT) (øC),TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (øC),TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (øC),UMIDADE REL. MAX. NA HORA ANT. (AUT) (%),UMIDADE REL. MIN. NA HORA ANT. (AUT) (%),"UMIDADE RELATIVA DO AR, HORARIA (%)","VENTO, DIREÇO HORARIA (gr) (ø (gr))","VENTO, RAJADA MAXIMA (m/s)","VENTO, VELOCIDADE HORARIA (m/s)"
0,01/01/2023,0000 UTC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,01/01/2023,0100 UTC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,01/01/2023,0200 UTC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,01/01/2023,0300 UTC,0.0,990.5,990.5,990.4,NaN,27.5,20.6,27.9,27.5,20.6,20.2,66.0,63.0,66.0,NaN,NaN,NaN
4,01/01/2023,0400 UTC,0.0,990.2,990.5,990.2,NaN,27.3,20.2,27.8,27.3,20.7,20.2,66.0,65.0,65.0,NaN,NaN,NaN

In [5]:
#Renomeando coluna do datasets
dataframe2023.rename(columns={'Hora UTC':'HORA (UTC)', 'RADIACAO GLOBAL (Kj/mý)': 'RADIACAO GLOBAL (KJ/mý)'}, inplace=True)
dataframe2003.rename(columns={'PRECIPITAÇÃO TOTAL, HORÁRIO (MM)': 'PRECIPITAÇÃO TOTAL, HORÁRIO (mm)'},inplace=True)



#Convertendo coluna DATA para datetime
dataframe2003['DATA'] = pd.to_datetime(dataframe2003['DATA'], format='%d/%m/%Y', errors='coerce').dt.strftime('%Y/%m/%d')
dataframe2013['DATA'] = pd.to_datetime(dataframe2013['DATA'], format='%d/%m/%Y', errors='coerce').dt.strftime('%Y/%m/%d')
dataframe2023['DATA'] = pd.to_datetime(dataframe2023['DATA'], format='%d/%m/%Y', errors='coerce').dt.strftime('%Y/%m/%d')

#Tratando HORA (UTC)
dataframe2023['HORA (UTC)'] = dataframe2023['HORA (UTC)'].str.rstrip(' UTC').str.slice_replace(2, 2, ':')

#Juntando datasets
df_concat = pd.concat([dataframe2003, dataframe2013, dataframe2023])
df_concat

,DATA,HORA (UTC),"PRECIPITAÇÃO TOTAL, HORÁRIO (mm)","PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)",PRESSÇO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB),PRESSÇO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB),RADIACAO GLOBAL (KJ/mý),"TEMPERATURA DO AR - BULBO SECO, HORARIA (øC)",TEMPERATURA DO PONTO DE ORVALHO (øC),TEMPERATURA MµXIMA NA HORA ANT. (AUT) (øC),TEMPERATURA MÖNIMA NA HORA ANT. (AUT) (øC),TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (øC),TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (øC),UMIDADE REL. MAX. NA HORA ANT. (AUT) (%),UMIDADE REL. MIN. NA HORA ANT. (AUT) (%),"UMIDADE RELATIVA DO AR, HORARIA (%)","VENTO, DIREÇO HORARIA (gr) (ø (gr))","VENTO, RAJADA MAXIMA (m/s)","VENTO, VELOCIDADE HORARIA (m/s)"
0,2003/01/01,00:00,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,24.3,23.3,24.7,24.3,23.4,-9999.0,94.0,92.0,94.0,-9999.0,-9999.0,-9999.0
1,2003/01/01,01:00,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,24.7,23.3,24.7,24.3,23.4,-9999.0,94.0,92.0,92.0,-9999.0,-9999.0,-9999.0
2,2003/01/01,02:00,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,24.4,23.2,24.7,24.4,23.4,-9999.0,93.0,91.0,93.0,-9999.0,-9999.0,-9999.0
3,2003/01/01,03:00,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,24.1,23.2,24.9,24.1,23.5,-9999.0,95.0,92.0,95.0,-9999.0,-9999.0,-9999.0
4,2003/01/01,04:00,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,24.5,23.4,24.6,24.1,23.5,-9999.0,95.0,93.0,94.0,-9999.0,-9999.0,-9999.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8755,2023/12/31,19:00,0.0,987.4,988.8,987.4,2575.3,34.4,19.4,35.2,33.9,20.6,19.1,45.0,40.0,41.0,320.0,6.6,3.0
8756,2023/12/31,20:00,0.0,986.7,987.4,986.7,1760.8,33.4,18.0,35.0,33.3,19.7,17.9,42.0,39.0,40.0,339.0,7.0,3.4
8757,2023/12/31,21:00,0.0,986.8,986.8,986.6,1127.5,32.5,21.8,33.9,32.1,22.0,18.0,55.0,40.0,53.0,105.0,6.0,2.0
8758,2023/12/31,22:00,0.0,986.9,987.0,986.8,490.1,30.8,21.8,32.7,30.8,21.9,21.3,59.0,52.0,59.0,96.0,4.0,1.5
8759,2023/12/31,23:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df_concat.replace(-9999.0, np.nan, inplace=True)

In [7]:
df_concat

,DATA,HORA (UTC),"PRECIPITAÇÃO TOTAL, HORÁRIO (mm)","PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)",PRESSÇO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB),PRESSÇO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB),RADIACAO GLOBAL (KJ/mý),"TEMPERATURA DO AR - BULBO SECO, HORARIA (øC)",TEMPERATURA DO PONTO DE ORVALHO (øC),TEMPERATURA MµXIMA NA HORA ANT. (AUT) (øC),TEMPERATURA MÖNIMA NA HORA ANT. (AUT) (øC),TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (øC),TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (øC),UMIDADE REL. MAX. NA HORA ANT. (AUT) (%),UMIDADE REL. MIN. NA HORA ANT. (AUT) (%),"UMIDADE RELATIVA DO AR, HORARIA (%)","VENTO, DIREÇO HORARIA (gr) (ø (gr))","VENTO, RAJADA MAXIMA (m/s)","VENTO, VELOCIDADE HORARIA (m/s)"
0,2003/01/01,00:00,NaN,NaN,NaN,NaN,NaN,24.3,23.3,24.7,24.3,23.4,NaN,94.0,92.0,94.0,NaN,NaN,NaN
1,2003/01/01,01:00,NaN,NaN,NaN,NaN,NaN,24.7,23.3,24.7,24.3,23.4,NaN,94.0,92.0,92.0,NaN,NaN,NaN
2,2003/01/01,02:00,NaN,NaN,NaN,NaN,NaN,24.4,23.2,24.7,24.4,23.4,NaN,93.0,91.0,93.0,NaN,NaN,NaN
3,2003/01/01,03:00,NaN,NaN,NaN,NaN,NaN,24.1,23.2,24.9,24.1,23.5,NaN,95.0,92.0,95.0,NaN,NaN,NaN
4,2003/01/01,04:00,NaN,NaN,NaN,NaN,NaN,24.5,23.4,24.6,24.1,23.5,NaN,95.0,93.0,94.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8755,2023/12/31,19:00,0.0,987.4,988.8,987.4,2575.3,34.4,19.4,35.2,33.9,20.6,19.1,45.0,40.0,41.0,320.0,6.6,3.0
8756,2023/12/31,20:00,0.0,986.7,987.4,986.7,1760.8,33.4,18.0,35.0,33.3,19.7,17.9,42.0,39.0,40.0,339.0,7.0,3.4
8757,2023/12/31,21:00,0.0,986.8,986.8,986.6,1127.5,32.5,21.8,33.9,32.1,22.0,18.0,55.0,40.0,53.0,105.0,6.0,2.0
8758,2023/12/31,22:00,0.0,986.9,987.0,986.8,490.1,30.8,21.8,32.7,30.8,21.9,21.3,59.0,52.0,59.0,96.0,4.0,1.5
8759,2023/12/31,23:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
#Definindo coluna data como indice
data = df_concat["DATA"].values
index = pd.DatetimeIndex(data, name="Data")
df_concat.drop("DATA", axis=1, inplace=True)
df_concat.set_index(index, inplace=True)
df_concat

,HORA (UTC),"PRECIPITAÇÃO TOTAL, HORÁRIO (mm)","PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)",PRESSÇO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB),PRESSÇO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB),RADIACAO GLOBAL (KJ/mý),"TEMPERATURA DO AR - BULBO SECO, HORARIA (øC)",TEMPERATURA DO PONTO DE ORVALHO (øC),TEMPERATURA MµXIMA NA HORA ANT. (AUT) (øC),TEMPERATURA MÖNIMA NA HORA ANT. (AUT) (øC),TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (øC),TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (øC),UMIDADE REL. MAX. NA HORA ANT. (AUT) (%),UMIDADE REL. MIN. NA HORA ANT. (AUT) (%),"UMIDADE RELATIVA DO AR, HORARIA (%)","VENTO, DIREÇO HORARIA (gr) (ø (gr))","VENTO, RAJADA MAXIMA (m/s)","VENTO, VELOCIDADE HORARIA (m/s)"
Data,,,,,,,,,,,,,,,,,,
2003-01-01,00:00,NaN,NaN,NaN,NaN,NaN,24.3,23.3,24.7,24.3,23.4,NaN,94.0,92.0,94.0,NaN,NaN,NaN
2003-01-01,01:00,NaN,NaN,NaN,NaN,NaN,24.7,23.3,24.7,24.3,23.4,NaN,94.0,92.0,92.0,NaN,NaN,NaN
2003-01-01,02:00,NaN,NaN,NaN,NaN,NaN,24.4,23.2,24.7,24.4,23.4,NaN,93.0,91.0,93.0,NaN,NaN,NaN
2003-01-01,03:00,NaN,NaN,NaN,NaN,NaN,24.1,23.2,24.9,24.1,23.5,NaN,95.0,92.0,95.0,NaN,NaN,NaN
2003-01-01,04:00,NaN,NaN,NaN,NaN,NaN,24.5,23.4,24.6,24.1,23.5,NaN,95.0,93.0,94.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-12-31,19:00,0.0,987.4,988.8,987.4,2575.3,34.4,19.4,35.2,33.9,20.6,19.1,45.0,40.0,41.0,320.0,6.6,3.0
2023-12-31,20:00,0.0,986.7,987.4,986.7,1760.8,33.4,18.0,35.0,33.3,19.7,17.9,42.0,39.0,40.0,339.0,7.0,3.4
2023-12-31,21:00,0.0,986.8,986.8,986.6,1127.5,32.5,21.8,33.9,32.1,22.0,18.0,55.0,40.0,53.0,105.0,6.0,2.0
2023-12-31,22:00,0.0,986.9,987.0,986.8,490.1,30.8,21.8,32.7,30.8,21.9,21.3,59.0,52.0,59.0,96.0,4.0,1.5
2023-12-31,23:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
df_concat.columns.tolist()
colunas = [
    ('HORA (UTC)',''),
 ('PRECIPITAÇÃO','PRECIPITAÇÃO TOTAL, HORÁRIO (mm)'),
 ('PRESSAO','PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)'),
 ('PRESSAO','PRESSÇO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB)'),
 ('PRESSAO','PRESSÇO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB)'),
 ('RADIACAO','RADIACAO GLOBAL (KJ/mý)'),
 ('TEMPERATURA','TEMPERATURA DO AR - BULBO SECO, HORARIA (øC)'),
 ('TEMPERATURA','TEMPERATURA DO PONTO DE ORVALHO (øC)'),
 ('TEMPERATURA','TEMPERATURA MµXIMA NA HORA ANT. (AUT) (øC)'),
 ('TEMPERATURA','TEMPERATURA MÖNIMA NA HORA ANT. (AUT) (øC)'),
 ('TEMPERATURA','TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (øC)'),
 ('TEMPERATURA','TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (øC)'),
 ('UMIDADE','UMIDADE REL. MAX. NA HORA ANT. (AUT) (%)'),
 ('UMIDADE','UMIDADE REL. MIN. NA HORA ANT. (AUT) (%)'),
 ('UMIDADE','UMIDADE RELATIVA DO AR, HORARIA (%)'),
 ('VENTO','VENTO, DIRE\x80ÇO HORARIA (gr) (ø (gr))'),
 ('VENTO','VENTO, RAJADA MAXIMA (m/s)'),
 ('VENTO','VENTO, VELOCIDADE HORARIA (m/s)')]

df_concat.columns = pd.MultiIndex.from_tuples(colunas)

3. Analise do dataframe

In [10]:
df_concat.groupby(df_concat.index.year)['PRECIPITAÇÃO'].aggregate(['min', 'mean', 'max'])

                         PRECIPITAÇÃO
     PRECIPITAÇÃO TOTAL, HORÁRIO (mm)
                                  min      mean   max
Data
2003                              0.0  0.105662  31.0
2013                              0.0  0.144678  59.0
2023                              0.0  0.124637  41.2

In [11]:
df_concat.groupby(df_concat.index.year)['TEMPERATURA'].aggregate(['min', 'mean', 'max'])

                                      TEMPERATURA                   \
     TEMPERATURA DO AR - BULBO SECO, HORARIA (øC)
                                              min       mean   max
Data
2003                                         12.2  26.072362  38.9
2013                                          8.9  26.319622  39.2
2023                                         10.0  28.599459  43.2

                                                            \
     TEMPERATURA DO PONTO DE ORVALHO (øC)
                                      min       mean   max
Data
2003                                  2.9  19.299684  24.9
2013                                 -4.3  18.643467  25.2
2023                                  3.8  17.604061  24.3

                                                                  \
     TEMPERATURA MµXIMA NA HORA ANT. (AUT) (øC)
                                            min       mean   max
Data
2003                                       13.5  26.722075  39.2
2013                                        9.1  26.924634  39.8
2023                                       10.2  29.279461  43.3

                                                                  \
     TEMPERATURA MÖNIMA NA HORA ANT. (AUT) (øC)
                                            min       mean   max
Data
2003                                       11.7  25.437100  38.0
2013                                        8.8  25.748959  37.7
2023                                        9.9  27.935143  42.0

                                                                        \
     TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (øC)
                                                  min       mean   max
Data
2003                                              3.8  19.833669  25.7
2013                                             -3.2  19.134039  25.8
2023                                              5.0  18.147457  24.9


     TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (øC)
                                                  min       mean   max
Data
2003                                              2.4  18.638451  24.2
2013                                             -6.4  18.166259  24.0
2023                                              2.9  17.089496  23.5

In [12]:
janeiro = df_concat.loc[df_concat.index.month == 1]
janeiro.groupby(janeiro.index.year)['PRECIPITAÇÃO'].aggregate(['min', 'mean', 'max'])

                         PRECIPITAÇÃO
     PRECIPITAÇÃO TOTAL, HORÁRIO (mm)
                                  min      mean   max
Data
2003                              0.0  0.226794  13.6
2013                              0.0  0.249462  18.0
2023                              0.0  0.373333  41.2

In [13]:
janeiro.groupby(janeiro.index.year)['TEMPERATURA'].aggregate(['min', 'mean', 'max'])

                                      TEMPERATURA                   \
     TEMPERATURA DO AR - BULBO SECO, HORARIA (øC)
                                              min       mean   max
Data
2003                                         22.7  26.809274  35.8
2013                                         22.7  26.451613  34.7
2023                                         22.1  27.461085  35.5

                                                            \
     TEMPERATURA DO PONTO DE ORVALHO (øC)
                                      min       mean   max
Data
2003                                 20.1  22.842204  24.9
2013                                 18.5  22.298790  25.2
2023                                 12.8  20.190853  23.0

                                                                  \
     TEMPERATURA MµXIMA NA HORA ANT. (AUT) (øC)
                                            min       mean   max
Data
2003                                       23.2  27.311156  35.8
2013                                       22.8  26.955780  35.0
2023                                       22.4  28.054264  35.8

                                                                  \
     TEMPERATURA MÖNIMA NA HORA ANT. (AUT) (øC)
                                            min       mean   max
Data
2003                                       22.5  26.307527  35.2
2013                                       22.4  25.956183  33.3
2023                                       22.0  26.847907  34.2

                                                                        \
     TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (øC)
                                                  min       mean   max
Data
2003                                             21.0  23.276747  25.7
2013                                             19.4  22.739382  25.8
2023                                             13.8  20.747597  23.7


     TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (øC)
                                                  min       mean   max
Data
2003                                             19.8  22.234211  23.9
2013                                             17.9  21.854570  24.0
2023                                             12.3  19.705891  22.4

In [14]:
verao = df_concat[(df_concat.index.month == 1) | (df_concat.index.month == 2) | (df_concat.index.month == 3)]
outono = df_concat[(df_concat.index.month == 4) | (df_concat.index.month == 5) | (df_concat.index.month == 6)]
inverno = df_concat[(df_concat.index.month == 7) | (df_concat.index.month == 8) | (df_concat.index.month == 9)]
primavera = df_concat[(df_concat.index.month == 10) | (df_concat.index.month == 11) | (df_concat.index.month == 12)]

In [15]:
print(verao.groupby(verao.index.year)['TEMPERATURA'].aggregate(['min', 'mean', 'max']))

                                      TEMPERATURA                   \
     TEMPERATURA DO AR - BULBO SECO, HORARIA (øC)
                                              min       mean   max
Data
2003                                         18.2  26.633534  35.8
2013                                         21.1  26.565733  35.8
2023                                         21.6  27.576530  36.1

                                                            \
     TEMPERATURA DO PONTO DE ORVALHO (øC)
                                      min       mean   max
Data
2003                                 16.3  22.442612  24.9
2013                                 15.3  22.038189  25.2
2023                                 12.8  20.555696  23.5

                                                                  \
     TEMPERATURA MµXIMA NA HORA ANT. (AUT) (øC)
                                            min       mean   max
Data
2003                                       18.3  27.165354  36.2
2013                                       21.4  27.088282  36.3
2023                                       21.7  28.189030  37.4

                                                                  \
     TEMPERATURA MÖNIMA NA HORA ANT. (AUT) (øC)
                                            min       mean   max
Data
2003                                       17.9  26.108893  35.2
2013                                       21.0  26.064706  34.7
2023                                       21.4  26.960707  35.5

                                                                        \
     TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (øC)
                                                  min       mean   max
Data
2003                                             16.7  22.921075  25.7
2013                                             16.4  22.519141  25.8
2023                                             13.8  21.109705  24.2


     TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (øC)
                                                  min       mean   max
Data
2003                                             16.3  21.874195  24.2
2013                                             14.6  21.574463  24.0
2023                                             12.3  20.047416  22.7

In [16]:
print(outono.groupby(outono.index.year)['TEMPERATURA'].aggregate(['min', 'mean', 'max']))

                                      TEMPERATURA                   \
     TEMPERATURA DO AR - BULBO SECO, HORARIA (øC)
                                              min       mean   max
Data
2003                                         14.1  25.303073  35.6
2013                                         16.1  25.731714  34.7
2023                                         10.0  25.895853  35.5

                                                            \
     TEMPERATURA DO PONTO DE ORVALHO (øC)
                                      min       mean   max
Data
2003                                  8.4  19.165229  24.6
2013                                 11.4  19.612236  24.9
2023                                  6.5  17.686067  24.0

                                                                  \
     TEMPERATURA MµXIMA NA HORA ANT. (AUT) (øC)
                                            min       mean   max
Data
2003                                       14.6  25.966055  36.1
2013                                       16.6  26.295692  34.8
2023                                       10.2  26.515610  36.0

                                                                  \
     TEMPERATURA MÖNIMA NA HORA ANT. (AUT) (øC)
                                            min       mean   max
Data
2003                                       13.9  24.656927  35.1
2013                                       16.0  25.199358  33.7
2023                                        9.9  25.312908  34.9

                                                                        \
     TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (øC)
                                                  min       mean   max
Data
2003                                              9.6  19.688165  25.5
2013                                             12.3  20.078002  25.0
2023                                              7.7  18.193150  24.3


     TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (øC)
                                                  min       mean   max
Data
2003                                              7.7  18.670183  23.8
2013                                             10.4  19.182631  23.4
2023                                              5.4  17.218639  23.3

In [17]:
print(inverno.groupby(inverno.index.year)['TEMPERATURA'].aggregate(['min', 'mean', 'max']))

                                      TEMPERATURA                   \
     TEMPERATURA DO AR - BULBO SECO, HORARIA (øC)
                                              min       mean   max
Data
2003                                         12.2  25.173822  38.9
2013                                          8.9  26.029891  39.2
2023                                         15.1  29.406840  41.4

                                                            \
     TEMPERATURA DO PONTO DE ORVALHO (øC)
                                      min       mean   max
Data
2003                                  2.9  14.684601  23.3
2013                                 -4.3  12.102989  21.9
2023                                  3.8  13.955951  23.3

                                                                  \
     TEMPERATURA MµXIMA NA HORA ANT. (AUT) (øC)
                                            min       mean   max
Data
2003                                       13.5  25.966078  39.2
2013                                        9.1  26.766803  39.8
2023                                       15.2  30.172230  41.8

                                                                  \
     TEMPERATURA MÖNIMA NA HORA ANT. (AUT) (øC)
                                            min       mean   max
Data
2003                                       11.7  24.401585  38.0
2013                                        8.8  25.340716  37.7
2023                                       14.7  28.675787  40.5

                                                                        \
     TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (øC)
                                                  min       mean   max
Data
2003                                              3.8  15.280299  23.8
2013                                             -3.2  12.621196  22.3
2023                                              5.0  14.498404  24.8


     TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (øC)
                                                  min       mean   max
Data
2003                                              2.4  14.119158  23.1
2013                                             -6.4  11.585507  21.5
2023                                              2.9  13.426676  22.2

In [23]:
print(primavera.groupby(primavera.index.year)['TEMPERATURA'].agg(['min', 'mean', 'max']))

                                      TEMPERATURA                   \
     TEMPERATURA DO AR - BULBO SECO, HORARIA (øC)
                                              min       mean   max
Data
2003                                         18.6  27.302008  37.7
2013                                         20.3  26.951585  37.4
2023                                         22.7  31.755285  43.2

                                                            \
     TEMPERATURA DO PONTO DE ORVALHO (øC)
                                      min       mean   max
Data
2003                                 11.5  21.155924  24.8
2013                                 11.5  20.933333  24.5
2023                                  5.6  18.781660  24.3

                                                                  \
     TEMPERATURA MµXIMA NA HORA ANT. (AUT) (øC)
                                            min       mean   max
Data
2003                                       18.7  27.906978  38.0
2013                                       20.6  27.545245  38.3
2023                                       23.1  32.482450  43.3

                                                                  \
     TEMPERATURA MÖNIMA NA HORA ANT. (AUT) (øC)
                                            min       mean   max
Data
2003                                       18.5  26.710592  37.3
2013                                       20.2  26.394022  36.4
2023                                       22.3  31.037275  42.0

                                                                        \
     TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (øC)
                                                  min       mean   max
Data
2003                                             13.1  21.693775  25.3
2013                                             11.8  21.430118  25.6
2023                                              8.8  19.360551  24.9


     TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (øC)
                                                  min       mean   max
Data
2003                                              8.4  20.635592  24.2
2013                                             10.9  20.436277  23.4
2023                                              5.3  18.227996  23.5

In [24]:
print(verao.groupby(verao.index.year)['PRECIPITAÇÃO'].aggregate(['min', 'mean', 'max']))
print(outono.groupby(outono.index.year)['PRECIPITAÇÃO'].aggregate(['min', 'mean', 'max']))
print(inverno.groupby(inverno.index.year)['PRECIPITAÇÃO'].aggregate(['min', 'mean', 'max']))
print(primavera.groupby(primavera.index.year)['PRECIPITAÇÃO'].aggregate(['min', 'mean', 'max']))

                         PRECIPITAÇÃO
     PRECIPITAÇÃO TOTAL, HORÁRIO (mm)
                                  min      mean   max
Data
2003                              0.0  0.205019  13.6
2013                              0.0  0.257610  59.0
2023                              0.0  0.312025  41.2
                         PRECIPITAÇÃO
     PRECIPITAÇÃO TOTAL, HORÁRIO (mm)
                                  min      mean   max
Data
2003                              0.0  0.077706  16.2
2013                              0.0  0.064312  34.0
2023                              0.0  0.095806  15.6
                         PRECIPITAÇÃO
     PRECIPITAÇÃO TOTAL, HORÁRIO (mm)
                                  min      mean   max
Data
2003                              0.0  0.000091   0.2
2013                              0.0  0.017754  10.4
2023                              0.0  0.020064  12.6
                         PRECIPITAÇÃO
     PRECIPITAÇÃO TOTAL, HORÁRIO (mm)
                                  min      mean   max
Data
2003                              0.0  0.161847  31.0
2013                              0.0  0.241395  48.4
2023                              0.0  0.090746  13.8

In [20]:
df_concat_periodo = df_concat.loc[df_concat.index.get_level_values("Data").month == 9]
df_concat_periodo = df_concat_periodo.loc[df_concat_periodo.index.get_level_values("Data").day == 28]
df_concat_periodo

           HORA (UTC)                     PRECIPITAÇÃO  \
                      PRECIPITAÇÃO TOTAL, HORÁRIO (mm)
Data
2003-09-28      00:00                              0.0
2003-09-28      01:00                              0.0
2003-09-28      02:00                              0.0
2003-09-28      03:00                              0.0
2003-09-28      04:00                              0.0
...               ...                              ...
2023-09-28      19:00                              0.0
2023-09-28      20:00                              0.0
2023-09-28      21:00                              0.0
2023-09-28      22:00                              0.0
2023-09-28      23:00                              NaN

                                                         PRESSAO  \
           PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)
Data
2003-09-28                                              980.3
2003-09-28                                              983.1
2003-09-28                                              984.5
2003-09-28                                              985.1
2003-09-28                                              985.7
...                                                       ...
2023-09-28                                              987.0
2023-09-28                                              986.2
2023-09-28                                              986.3
2023-09-28                                              987.0
2023-09-28                                                NaN

                                                            \
           PRESSÇO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB)
Data
2003-09-28                                           980.3
2003-09-28                                           983.1
2003-09-28                                           984.5
2003-09-28                                           985.1
2003-09-28                                           985.7
...                                                    ...
2023-09-28                                           987.8
2023-09-28                                           987.0
2023-09-28                                           986.3
2023-09-28                                           987.0
2023-09-28                                             NaN

                                                             \
           PRESSÇO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB)
Data
2003-09-28                                            979.1
2003-09-28                                            980.3
2003-09-28                                            983.1
2003-09-28                                            984.5
2003-09-28                                            985.1
...                                                     ...
2023-09-28                                            987.0
2023-09-28                                            986.2
2023-09-28                                            986.1
2023-09-28                                            986.3
2023-09-28                                              NaN

                          RADIACAO  \
           RADIACAO GLOBAL (KJ/mý)
Data
2003-09-28                     NaN
2003-09-28                     NaN
2003-09-28                     NaN
2003-09-28                     NaN
2003-09-28                     NaN
...                            ...
2023-09-28                  2318.9
2023-09-28                  1541.4
2023-09-28                   680.8
2023-09-28                    74.5
2023-09-28                     NaN

                                            TEMPERATURA  \
           TEMPERATURA DO AR - BULBO SECO, HORARIA (øC)
Data
2003-09-28                                         27.1
2003-09-28                                         27.4
2003-09-28                                         25.5
2003-09-28                                         24.7
2003-09-28                                         24.3
...                                                 ...
2023-09-28                                         34.1
2023-09-28                                         33.5
2023-09-28                                         33.3
2023-09-28                                         32.3
2023-09-28                                          NaN

                                                 \
           TEMPERATURA DO PONTO DE ORVALHO (øC)
Data
2003-09-28                                 22.0
2003-09-28                                 21.2
2003-09-28                                 23.0
2003-09-28                                 22.6
2003-09-28                                 22.4
...                                         ...
2023-09-28                                 17.1
2023-09-28                                 17.2
2023-09-28                                 18.0
2023-09-28                                 18.6
2023-09-28                                  NaN

                                                       \
           TEMPERATURA MµXIMA NA HORA ANT. (AUT) (øC)
Data
2003-09-28                                       28.2
2003-09-28                                       27.8
2003-09-28                                       27.4
2003-09-28                                       25.5
2003-09-28                                       24.7
...                                               ...
2023-09-28                                       34.1
2023-09-28                                       34.5
2023-09-28                                       34.3
2023-09-28                                       33.3
2023-09-28                                        NaN

                                                       \
           TEMPERATURA MÖNIMA NA HORA ANT. (AUT) (øC)
Data
2003-09-28                                       26.5
2003-09-28                                       26.5
2003-09-28                                       25.5
2003-09-28                                       24.7
2003-09-28                                       24.3
...                                               ...
2023-09-28                                       32.3
2023-09-28                                       33.2
2023-09-28                                       33.3
2023-09-28                                       32.3
2023-09-28                                        NaN

                                                             \
           TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (øC)
Data
2003-09-28                                             22.1
2003-09-28                                             22.6
2003-09-28                                             23.1
2003-09-28                                             23.0
2003-09-28                                             22.6
...                                                     ...
2023-09-28                                             18.0
2023-09-28                                             17.7
2023-09-28                                             18.1
2023-09-28                                             18.6
2023-09-28                                              NaN

                                                             \
           TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (øC)
Data
2003-09-28                                             21.2
2003-09-28                                             21.1
2003-09-28                                             21.2
2003-09-28                                             22.6
2003-09-28                                             22.3
...                                                     ...
2023-09-28                                             16.8
2023-09-28                                             16.8
2023-09-28                                             16.9
2023-09-28                                             17.8
2023-09-28                                              NaN

                                            UMIDADE  \
           UMIDADE REL. MAX. NA HORA ANT. (AUT) (%)
Data
2003-09-28                                     76.0
2003-09-28                                     79.0
2003-09-28                                     86.0
2003-09-28                                     88.0
2003-09-28                                     89.0
...                                             ...
2023-09-28                                     41.0
2023-09-28                                     38.0
2023-09-28                                     40.0
2023-09-28                                     44.0
2023-09-28                                      NaN

                                                     \
           UMIDADE REL. MIN. NA HORA ANT. (AUT) (%)
Data
2003-09-28                                     66.0
2003-09-28                                     67.0
2003-09-28                                     69.0
2003-09-28                                     85.0
2003-09-28                                     87.0
...                                             ...
2023-09-28                                     36.0
2023-09-28                                     36.0
2023-09-28                                     37.0
2023-09-28                                     40.0
2023-09-28                                      NaN

                                                \
           UMIDADE RELATIVA DO AR, HORARIA (%)
Data
2003-09-28                                74.0
2003-09-28                                69.0
2003-09-28                                86.0
2003-09-28                                88.0
2003-09-28                                89.0
...                                        ...
2023-09-28                                37.0
2023-09-28                                38.0
2023-09-28                                40.0
2023-09-28                                44.0
2023-09-28                                 NaN

                                          VENTO                             \
           VENTO, DIREÇO HORARIA (gr) (ø (gr)) VENTO, RAJADA MAXIMA (m/s)
Data
2003-09-28                                 71.0                        1.8
2003-09-28                                 73.0                        2.1
2003-09-28                                240.0                        1.8
2003-09-28                                276.0                        2.3
2003-09-28                                308.0                        2.3
...                                         ...                        ...
2023-09-28                                278.0                        3.9
2023-09-28                                209.0                        3.6
2023-09-28                                212.0                        3.6
2023-09-28                                192.0                        3.1
2023-09-28                                  NaN                        NaN


           VENTO, VELOCIDADE HORARIA (m/s)
Data
2003-09-28                             0.8
2003-09-28                             0.8
2003-09-28                             1.1
2003-09-28                             0.6
2003-09-28                             0.1
...                                    ...
2023-09-28                             0.9
2023-09-28                             1.6
2023-09-28                             1.3
2023-09-28                             0.7
2023-09-28                             NaN

[72 rows x 18 columns]

In [21]:
# vendo valores de hora
print((df_concat_periodo)['HORA (UTC)'].unique())

['00:00' '01:00' '02:00' '03:00' '04:00' '05:00' '06:00' '07:00' '08:00'
 '09:00' '10:00' '11:00' '12:00' '13:00' '14:00' '15:00' '16:00' '17:00'
 '18:00' '19:00' '20:00' '21:00' '22:00' '23:00']

In [22]:
horas = {'00:00': 'madrugada', '01:00': 'madrugada', '02:00': 'madrugada', '03:00': 'madrugada', '04:00': 'madrugada', '05:00': 'madrugada',
           '06:00': 'manha', '07:00': 'manha', '08:00': 'manha', '09:00': 'manha', '10:00': 'manha', '11:00': 'manha', '12:00': 'manha',
           '13:00': 'tarde', '14:00': 'tarde', '15:00': 'tarde', '16:00': 'tarde', '17:00': 'tarde', '18:00': 'tarde',
           '19:00': 'noite', '20:00': 'noite', '21:00': 'noite', '22:00': 'noite', '23:00': 'noite'}

temperatura = df_concat_periodo.groupby('HORA (UTC)')['TEMPERATURA'].mean()
precipitacao_hora = df_concat_periodo.groupby('HORA (UTC)')['PRECIPITAÇÃO'].mean()

# concatenando os dataframes
prec_temp_por_hora = pd.concat([precipitacao_hora, temperatura], axis=1)
prec_temp_por_hora.groupby(horas).mean()

                               PRECIPITAÇÃO  \
           PRECIPITAÇÃO TOTAL, HORÁRIO (mm)
HORA (UTC)
madrugada                          0.000000
manha                              0.009524
noite                              0.000000
tarde                              0.000000

                                            TEMPERATURA  \
           TEMPERATURA DO AR - BULBO SECO, HORARIA (øC)
HORA (UTC)
madrugada                                     27.833333
manha                                         25.200000
noite                                         32.753333
tarde                                         32.327778

                                                 \
           TEMPERATURA DO PONTO DE ORVALHO (øC)
HORA (UTC)
madrugada                             17.641667
manha                                 17.328571
noite                                 18.243333
tarde                                 17.855556

                                                       \
           TEMPERATURA MµXIMA NA HORA ANT. (AUT) (øC)
HORA (UTC)
madrugada                                   28.691667
manha                                       25.633333
noite                                       33.743333
tarde                                       32.661111

                                                       \
           TEMPERATURA MÖNIMA NA HORA ANT. (AUT) (øC)
HORA (UTC)
madrugada                                   27.661111
manha                                       24.542857
noite                                       32.480000
tarde                                       30.822222

                                                             \
           TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (øC)
HORA (UTC)
madrugada                                         18.166667
manha                                             17.623810
noite                                             18.613333
tarde                                             18.494444


           TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (øC)
HORA (UTC)
madrugada                                         17.269444
manha                                             16.928571
noite                                             17.706667
tarde                                             17.216667